### ISSUE TITLE
Allow configuration of LDAP connection authentication mechanism

### ISSUE THREAD

**Issue by ClifHouck** [rroemhild/flask-ldapconn#1]
Refer to: https://github.com/rroemhild/flask-ldapconn/blob/master/flask_ldapconn.py#L116

This line forces the connection to use the simple authentication method. Why not allow the user to specify the type of authentication they want? 

Personally I want to use the anonymous authentication method.

**Comment by rroemhild** [comment]
Thank you for this hint, anonymous auth works now on version 0.3.3. I will look into SASL auth another time. 

Regards
