### ISSUE TITLE
use of "personal" connections

### ISSUE THREAD

**Issue by extmind** [rroemhild/flask-ldapconn#12]
My use case is basically that a user logs into (using authenticate()) the app and changes his personal data (e.g. mail). The server is configured that you can query a user without binding using a password, so I do not need to store the admin password in a plain text file and a user binding with his own password may only ever change attributes he is entitled to.
But to change a users data, I would need his connection (as in authenticate()) instead of the general connection of the app (as configured in the plain text config). Given that, I think I would need to replace the original connection somehow and maybe even use the LDAPEntry object for flask-login (that also does not work, at least in the obvious way). Or am I missing something?

Is what I describe here possible to achieve with flask-ldapconn? If so, how?

**Comment by rroemhild** [comment]
I think I finally found a good solution (352273f) for this. With Version 0.6.7 you can save a connection to the flask.g object and the connection handler will use this connection for the current request.

```
flask.g.ldap_conn = ldap.connect(binddn, secret)
```
