### ISSUE TITLE
access the initialized LDAPConn from blueprints

### ISSUE THREAD

**Issue by SkyLeach** [rroemhild/flask-ldapconn#18]
I wasn't able to find anything about this in the docs.

after application initialization I need access to the LDAPConn object.  I can't simply import it because these are blueprints, which means that they have to be imported by the application configuration and thus can't import the application configuration without circular import problems.

The documentation considers only simple setups.

So here I am forced to use current_app to access the application.  ldap = LDAPConn(current_app) doesn't work, however.  It yields: 
`AssertionError: A setup function was called after the first request was handled. This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late. To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.`

I can't init and import, and I can't init in the authentication module itself.  I CAN hack the app to store the object, but before I do this I wanted to know if there is an undocumented way to get at LDAPConn through the app (using current_app)?

**Comment by rroemhild** [comment]
Hi, yes this project is very undocumented, sorry. Maybe it works if you get the object from the ctx ```ldap = current_app.extensions.get('ldap_conn')```.

**Comment by rroemhild** [comment]
Import from your app should also work. ```from myapp import ldap```.

**Comment by SkyLeach** [comment]
can't import from the app.  blueprints have to be imported during app init which would create a circular import.

Right now I'm having to do the following (which means i can't use decorators in blueprints):

``myapp/__init__.py``
`
from .utils import load_user

def createApp():
   <... other app init stuff ...>
   app.ldap = LDAPConn(app)
   app.login_module = LoginModule(app)
   app.login_module.user_loader(load_user)
`

``myapp/utils.py``
`# can't use decorator
#login_module.user_loader
def load_user():
    current_app.ldap.connection( <args> )
`

I've asked the guys in #pocoo (freenode) to consider adding formal add-on naming into the Flask docs for this kind fo thing.  We'll see if they do it.

**Comment by SkyLeach** [comment]
this does, however, look like something that might be useful:

`ldap = current_app.extensions.get('ldap_conn')`
