### ISSUE TITLE
Source tarball improvements

### ISSUE THREAD

**Issue by Natureshadow** [rroemhild/flask-ldapconn#22]
I am maintaining Flask-LDAPConn in Debian and have the following remarks:

 * Please include the changelog in the source tarball.
 * Please sign the source tarball published on PyPI

**Comment by Natureshadow** [comment]
Please also be less strict on dependencies. I see no good reason for limiting the install_requires so much, I'd only set ldap3 to before verion 2.0.

**Comment by rroemhild** [comment]
Thanks for maintaining Flask-LDAPConn in Debian and for your contribution to this project. I signed the latest version on PyPi.
