### ISSUE TITLE
Intention on forking the project

### ISSUE THREAD

**Issue by leo-labs** [rroemhild/flask-ldapconn#28]
I would like to use the code in this project as a starting point for an LDAP3 ORM that does not depend necessarily on flask, that is splitting the current project into two projects `ldap3_orm` and `ldap3_orm_flask`. 
I am also planning to implement new features, e.g. inheritance for the model. 
Since those changes could not easily merged back into this project I do not plan on using githubs fork button, but just push the current state to a new repository and work from there. 
Please let me know what do you think about those plans!

**Comment by rroemhild** [comment]
That would be great! I like this project but actually have not the time to work on this. And there is lot of space for improvements :smile: Your idea to split this into 2 projects sound good for me. I'm happy that you want to improve and to continue on such a project, even if it's not forked. Let me hear about your success.
