### ISSUE TITLE
List attribute access does not work (as before/as expected)

### ISSUE THREAD

**Issue by henryk** [rroemhild/flask-ldapconn#29]
The fix/change in #24 and #25 mostly breaks working with list attributes in any sensible/easy or obviously correct way. As hinted to in the comment for b59c49599f04eb153b62f47886df8e4d2c624733 a field is either a list or it is not a list, but there's no way to indicate that in the model, and #24 makes accessing it much harder.

## Steps to reproduce:
1. Create the following model
````
class Test(ldap.Entry):
	object_classes = ['groupOfNames']
	entry_rdn = ['cn', 'base_dn']

	name = ldap.Attribute('cn')
	members = ldap.Attribute('member', default=[])
````
2. Create two objects of this type in LDAP: `object1` should have 1 `member` attribute value (`foo`), `object2` should have 2 `member` attribute values (`bar` and `baz`).
3. `print ", ".join(object1.members)`
4. `print ", ".join(object2.members)`

## Expected results (flask-ldapconn<0.7.0)
- At step 3:  `foo`
- At step 4:  `bar, baz`

## Actual results (flask-ldapconn>=0.7.0)
- At step 3: `f, o, o`
- At step 4: `bar, baz`

## Explanation
For basically all objects with multivalued attributes the accessing code does not want to care whether currently there's only one item in the list or multiple items. Example: I want to display the list with comma-separated values (`", ".join(…)`). With the new behaviour I would have to add a case distinction (along the lines of `object1.members if isinstance(object1.members, str) else ", ".join(object1.members)`).

Beginning with #24 all attribute access in `LDAPEntry` is delegated to the `LDAPAttribute` `value` property which conditionally returns a single value *or* a list of values. It's now impossible to access the `LDAPAttribute` `values` list to work around the behaviour of the `value` getter.

The two only workarounds I see:
- Access the `LDAPEntry._attributes` internal property directly. (`", ".join(object1._attributes["members"].values)`)
- Go through `get_attributes_dict()`:  `", ".join(object1.get_attributes_dict()["members"])`

The most preferred solution would be some way to declare an LDAPAttribute to be a list and circumvent all "now it's a list, now it's a string, you can never know" magic.

**Comment by rroemhild** [comment]
Hi @henryk, I'm with you. The question of is it a list or a string is confusing. I think we should only return lists. That's how LDAP handle Attributes so everyone should expect lists instead of a string.

**Comment by gcavalcante8808** [comment]
Hello Folks,

Im in proccess to simplify/reorganize a system written in django, and for that, I'm prospecting this lib; but I cant append new entries to list attributes (we have a custom schema to work with a bunch of Moodles, and courseStudent is an Attr derived from member).

I have the following code:

##Models.py
```
from flask_ldapconn import LDAPEntry, LDAPAttribute

class LdapCourse(LDAPEntry):
    base_dn = 'dc=example,dc=com'
    object_classes = ['organization', 'moodleCourse']
    entry_rdn = ['cn']

    shortname = LDAPAttribute('cn')
    fullname = LDAPAttribute('title')
    description = LDAPAttribute('description')

    project = LDAPAttribute('o')

    students = LDAPAttribute('courseStudent', default=[])
    managers = LDAPAttribute('courseManager', default=[])
    teachers = LDAPAttribute('courseTeacher', default=[])
    guests = LDAPAttribute('courseGuest', default=[])
    non_editing_teachers = LDAPAttribute('courseNonEditingTeacher', default=[])
    authenticated_users = LDAPAttribute('courseAuthenticatedUser', default=[])
    authenticated_frontpage_users = LDAPAttribute('courseAuthenticatedFrontPage', default=[])

    def __str__(self):
        return self.shortname

    def __unicode__(self):
        return self.shortname
```

Tests.py
```
 ....
    def test_ldap_course_ops(self):
        with app.app.app_context():
            course = msm.models.LdapCourse()
            course.shortname = 'NewCourse'
            course.fullname = 'This is The New Course'
            course.project = 'NewProjectINC'
            created = course.save()
            self.assertTrue(created)

            course.students.append(self.student.dn)
            enrolled = course.save()
            self.assertTrue(enrolled) <-- Never returns True
```

Openldap Logs (LEVEL 4)

```
5a8c326a connection_get(12)
5a8c326a conn=1003 op=9 do_add: dn (cn=NewCourse,dc=example,dc=com)
=> ldap_bv2dn(cn=NewCourse,dc=example,dc=com,0)
<= ldap_bv2dn(cn=NewCourse,dc=example,dc=com)=0 
=> ldap_dn2bv(272)
<= ldap_dn2bv(cn=NewCourse,dc=example,dc=com)=0 
=> ldap_dn2bv(272)
<= ldap_dn2bv(cn=newcourse,dc=example,dc=com)=0 
=> ldap_bv2dn(uid=74666806237,dc=example,dc=com,0)
<= ldap_bv2dn(uid=74666806237,dc=example,dc=com)=0 
=> ldap_dn2bv(272)
<= ldap_dn2bv(uid=74666806237,dc=example,dc=com)=0 
=> ldap_bv2dn(uid=74666806237,dc=example,dc=com,0)
<= ldap_bv2dn(uid=74666806237,dc=example,dc=com)=0 
=> ldap_dn2bv(272)
<= ldap_dn2bv(uid=74666806237,dc=example,dc=com)=0 
5a8c326a ==> mdb_add: cn=NewCourse,dc=example,dc=com
5a8c326a send_ldap_result: err=68 matched="" text=""
```

Thanks in advance.

**Comment by rroemhild** [comment]
@henryk does 2143e34 address your issue? I thought it would be better to make a config variable. As seen in ldap3 code, they also return a str() if only one object is stored in the attribute value list. So i'll let this default an if you want, set `FORCE_ATTRIBUTE_VALUE_AS_LIST = True` and you always get a list.

**Comment by rroemhild** [comment]
Feel free to re-open this issue if this is no solution for you.

@gcavalcante8808 your issue looks like a different problem. To me it looks like a problem with your schemas. Maybe a missing MUST attribute. Please open a new issue if you still have this issue.
