### ISSUE TITLE
[question] single values as string

### ISSUE THREAD

**Issue by rbw0** [rroemhild/flask-ldapconn#31]
I'm able to obtain a list of `Entry` objects and convert these to dictionaries for JSON serialization using `get_attributes_dict()`.
The result is a list of objects containing the expected properties - however, values are contained in lists; Is there an easy way to get "single value" properties as string instead?

BTW - I noticed `LDAPAttribute` is missing some features available in `AttrDef`, such as `post_query`. Any plans on implementing those?

Anyway - thank you for a great extension.

Have a good day

**Comment by rroemhild** [comment]
Hi, "single values" as string from `get_attributes_dict() is not supported, it would break the LDAP modify method.

You can try to iterate over `entry._attributes.keys()` and get the values from the `value` property for each key:

```python
with app.app_context():

    user = User.query.filter('userid: fry').first()
    json_entry = dict()
    json_entry['dn'] = user.dn
    json_entry['attributes'] = {}

    for attr in user._attributes.keys():
        json_entry['attributes'][attr] = user._attributes[attr].value

    json_output = json.dumps(json_entry,
                             ensure_ascii=True,
                             sort_keys=True,
                             indent=2,
                             check_circular=True,
                             default=format_json,
                             separators=(',', ': '))

    print(json_output)
```

Actually there is no plan to implement missing features. But feel free to open this as a new Issue, maybe I find time to look into this or a pull request :)

**Comment by rroemhild** [comment]
As of writing this snippet I recognized that this could be easy implemented in `Entry.to_json()` :smile:

**Comment by rbw0** [comment]
Thanks for the quick reply.

Implementing this in `Entry.to_json()` sounds like a good idea :+1:

**Comment by rroemhild** [comment]
I've add a PR to address this. Let me know if this works for you.

**Comment by rbw0** [comment]
Works great :+1:

**Comment by rroemhild** [comment]
Merged into master. Have to look into CI problem with python 3.4 before I'll release a new version.

**Comment by rroemhild** [comment]
Uploaded 0.7.2 to pypi.
