### ISSUE TITLE
New release version on PyPI?

### ISSUE THREAD

**Issue by northwestwitch** [rroemhild/flask-ldapconn#69]
Hi! I noticed that the release from last week is still missing on [PyPI](https://pypi.org/project/Flask-LDAPConn/). Would it be possible to add it? Many thanks!

**Comment by rroemhild** [comment]
Sorry for the delay. It's been a long time since I uploaded anything to pipy. I just uploaded the latest release.

**Comment by northwestwitch** [comment]
Thank you!!! 🚀
